site_name: Cronjobly Documentation
site_url: https://docs.cronjobly.com
site_description: Cronjobly is a dynamic content personalization platform that delivers tailored experiences to users based on real-time context and behavior.
site_author: omegion

edit_uri: https://github.com/cronjobly/docs/blob/main/docs/

docs_dir: docs
site_dir: site
copyright: <script>document.write(new Date().getFullYear())</script> &copy; <a href="https://cronjobly.com" target="_blank">Cronjobly</a> &bull; Made with ❤️ in Berlin

nav:
  - Home: index.md


theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/favicons/favicon.ico
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: pink
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - toc.follow
    - toc.integrates
    - content.tooltips
    - search.suggest
    - search.highlight
extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  analytics:
    provider: google
    property: G-C585YQ9GVB
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cronjobly
      name: Official Cronjobly GitHub Page
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: cronjobly/docs
      branch: main
      token: !ENV ["GITHUB_TOKEN"]
